### ISSUE TITLE
The use-package based installation doesn't work.

### ISSUE THREAD

**Issue by hongyi-zhao** [emacs-openai/chatgpt#12]
I try to use the following command to install this package: `(use-package chatgpt :ensure t)`.

But the following error is encountered:

```elisp
Warning (initialization): An error occurred while loading ‘/home/werner/.emacs.d/init.el’:

error: Could not find package chatgpt. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror nongnu-elpa el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
See https://github.com/radian-software/straight.el/issues/1084#issuecomment-1544133412 for the related discussion.

**Comment by hongyi-zhao** [comment]
See https://github.com/radian-software/straight.el/issues/1084#issuecomment-1544824928 for the related comments.

**Comment by jcs090218** [comment]
Oh, I think I understand it.

You should use `:straight` keyword instead:

```elisp
(use-package chatgpt
  :straight (chatgpt :type git :host github :repo "emacs-openai/chatgpt"))
```

**Comment by jcs090218** [comment]
Closing this due to no new activities. Feel free to open a new one if the issue persist! ;)
