### ISSUE TITLE
Doom emacs installation seemed to work, but I consistently get "429 - Rate limit reached for requests"

### ISSUE THREAD

**Issue by johnabs** [emacs-openai/chatgpt#13]
I installed using doom emacs' package! macro and installed both openai and chatgpt. Eveything seems to behave correctly except submitting the actual requests.

`
(package! openai
  :recipe (:host github :repo "emacs-openai/openai"))
(package! chatgpt
  :recipe (:host github :repo "emacs-openai/chatgpt"))
`

And added my api key in my config file, but all attempts at submitting responses fail with the aforementioned error message.

Any ideas, and is there any other info you may need from me to diagnose the problem?

Best,
John

**Comment by jcs090218** [comment]
The error says it all. Are you using the free version? They want you to pay them for more services.

Hope the information helps! ;)

**Comment by johnabs** [comment]
Oh, I'm using the free version, but I can keep making normal requests on the "Try Chatgpt" website, so I'm unsure why the rate limit is reached for emacs but not for my browser.

**Comment by jcs090218** [comment]
Browser uses a different rate limit. I can do it on the browser too, but not over the Rest API.

**Comment by jcs090218** [comment]
Since there is nothing we can do on our side, therefore closing this issue!

Feel free to open a new issue if you have other concerns! ;)

**Comment by johnabs** [comment]
Good catch, thanks for your help!
