### ISSUE TITLE
Package installation instructions do not mention that "opeanai" dependency needs to be installed as well.

### ISSUE THREAD

**Issue by progfolio** [emacs-openai/chatgpt#25]
The installation instructions for the package mention that it is available through "JCS-ELPA", which I'm assuming also hosts the "openai" package (there were no installation instructions for that library in it's repo README).
Users of package managers like straight.el or Elpaca will try to install the package directly from this repo via your recipe:

```emacs-lisp
(use-package chatgpt
  :straight (chatgpt :type git :host github :repo "emacs-openai/chatgpt"))
```

However, that will fail, because they will not have JCS-ELPA's recipes available.
See: https://github.com/progfolio/elpaca/issues/199
Perhaps that should be mentioned and the installation instructions should include the declaration for "openai" and any other dependencies which are necessary and not available through the widely-used ELPAs. e.g.

```emacs-lisp
(use-package openai ...) ;; Necessary if you do not have JCS-ELPA as a source for your package manager.
(use-package chatgpt
  :straight (chatgpt :type git :host github :repo "emacs-openai/chatgpt"))
```

**Comment by jcs090218** [comment]
Sorry for the late reply. This somehow goes under my radar. Would you like to open a PR for this? Thank you!

**Comment by progfolio** [comment]
I don't use the package, so I'm not interested in opening a pull request.
I brought this to your attention because I received bug reports on the package managers I maintain about this issue.
Please fix for your users.
