### ISSUE TITLE
Got 400 error during conversation

### ISSUE THREAD

**Issue by jcubic** [emacs-openai/chatgpt#28]
During conversation, I got 400 errors:

```
[error] request--callback: peculiar error: 400
400 - Bad request.  Please check error message and your parameters
```

an no way to debug. I can give you the whole conversation I was asking about my elisp code.

**EDIT:** when I got about 1800 tokens (I got this indicator at the bottom) the chat stoped responding. When I reset the chat I got 400 errors.

**Comment by jcubic** [comment]
when I got about 1800 tokens (I got this indicator at the bottom) the chat stoped responding. When I reset the chat I got 400 errors.

**Comment by jcs090218** [comment]
Check our debugging section, see https://github.com/emacs-openai/openai#-debugging.

It should print out the reason why the message failed. 🤔

**Comment by jcubic** [comment]
Unfortunately I've reset the session. I'm closing this now but I will reopen when this happen again I will check the logs when it occurs again.
