### ISSUE TITLE
[feature request] make prompt answers appear gradually

### ISSUE THREAD

**Issue by benthamite** [emacs-openai/chatgpt#3]
Currently, prompt answers appear only after GPT is finished, rather than being displayed gradually, word by word. The latter seems preferable because one can read the answer immediately rather than have to wait 10–30 seconds for GPT to finish. Could this be implemented?

**Comment by jcs090218** [comment]
You mean non-blocking inputs? Or the text animation? The text will be display immediately after it receives the response.

**Comment by jcs090218** [comment]
The text animation is implemented in #4. LMKWYT? :D

**Comment by benthamite** [comment]
Thanks. I thought the animation wasn't merely cosmetic but that it reflected the pace at which GPT would deliver the text via the API. But it looks like I was mistaken? In any case, thanks for implementing this.

**Comment by jcs090218** [comment]
Yeah, the text animation in unrelated to the request itself! Thank you for opening a feature request! 🚀 :D
