### ISSUE TITLE
My moon animation isn't working

### ISSUE THREAD

**Issue by jfy4** [emacs-openai/chatgpt#33]
Hi,

I see in the demos there is a little moon animation in the top corner when the bot is working.  Mine doesn't have that, there is instead some square of numbers and letters that change rapidly.  Everything else seems to work great.  Any idea why that isn't working?

Thanks

**Comment by jcs090218** [comment]
The animation is a sequence of characters. Make sure those characters are available (install those fonts) on your machine.

Or, you can change the animation by:

```elisp
(setq chatgpt-spinner-type 'moon)  ; Replace 'moon to something else.
```

**Comment by jfy4** [comment]
Thanks! Do you happen to know what the fonts are?

**Comment by jcs090218** [comment]
I'm not 100 percent sure, but `Symbola` is the font that display on my machine (Windows 11).

**Comment by jfy4** [comment]
That did it, thanks!
