### ISSUE TITLE
makes git version of emacs freez

### ISSUE THREAD

**Issue by mrfluffy-dev** [emacs-openai/chatgpt#6]
Emacs Version:GNU Emacs 30.0.50
Doom emacs
OS: Arch Linux

# packages.el
```elisp
(package! openai
  :recipe (:host github :repo "emacs-openai/openai" :files ("*.el")))
(package! chatgpt
  :recipe (:host github :repo "emacs-openai/chatgpt" :files ("*.el")))
```
config.el
```elisp
(setq openai-key (getenv "OPENAIKEY"))
(setq chatgpt-input-method 'minibuffer)
```

I wish I had more info on what the problem is but all I know is when I am on Emacs 30.0.50 my entire amacs locks op and doesn't load when I use this package I cant check logs coz emacs is frozen. The package works just fine on Emacs 28.2-2 I would be happy to give any more info.

**Comment by jcs090218** [comment]
Can you elaborate when or what make Emacs frozen? Does it crash on startup? On load time? After `(require ...`? etc.

Since I don't have your environment, I would need you to do some tests.

1. Check upstream. Can you require these packages one by one? My best guess is requiring [openai](https://github.com/emacs-openai/openai).

https://github.com/emacs-openai/chatgpt/blob/d5e773de2b31a1227d8e1a8946c99e8691bcf375/chatgpt.el#L34-L42

2. Try to print something. Before your Emacs got frozen, you should able to print at the very beginning of the operation. For example,

```elisp
(require 'chatgpt)  ; load it for overwrite, this line assumed no upstream error (Pt. 1)
```

```diff
;;;###autoload
(defun chatgpt ()
  "Start ChatGPT with existing instance, else create a new instance."
  (interactive)
+  (message "Test 1")
  (let ((live-instances  (chatgpt--live-instances))
        (shown-instances (chatgpt--shown-instances)))
+    (message "Test 2")  ; if this doesn't get print, something wrong before this
    (cond (shown-instances
           (chatgpt--pop-to-buffer (nth 0 shown-instances)))
          (live-instances
           (chatgpt--pop-to-buffer (nth 0 live-instances)))
          (t
           (chatgpt-new)))))
```

**Comment by mrfluffy-dev** [comment]
Its hard to explain. when I open Emacs (non daemon) I would want to see the my Doom buffer but I see nothing just white. I can do M-x and the menu pops up but selecting anything or closing it makes Emacs unresponsive again ill remove 
```elisp
(package! chatgpt
  :recipe (:host github :repo "emacs-openai/chatgpt" :files ("*.el")))
 ```
but keep openAI if it still crashes I know which of the 2 causes the problem. 
if it doesn't crash Ill do the `(require '*)` one by one in my open el file and tell you the results.

**Comment by mrfluffy-dev** [comment]
Ok I think I got the problem its cl-lib everything else doesn't make it crash and running `emacs --daemon` does give some logs I can work with and that is `Package cl is deprecated` don't know how hard it will be not to rely on cl but It would probably be a good idea to see if you can make this work without it. seeing as emacs has dropped it.

**Comment by mrfluffy-dev** [comment]
Ok I found the problem this time it doesn't seem to be you at all I suspect the GNU boys messed something up with the latest pull went back to 30.0.50 from back 2023-03-19 and it works just fine. so somewhere between the 19th and today they fucked up something. But thanks for the help.

**Comment by jcs090218** [comment]
No worries! I was suspecting myself using any `cl` functions. Happy you find the solution yourself! :D

Since this issue is due to upstream, therefore closing it.
