### ISSUE TITLE
Where do you put the API Key

### ISSUE THREAD

**Issue by joshagudo** [emacs-openai/chatgpt#7]
> Copy the key and paste into the 'API Key' field under the 'openai' custom group settings.

Are you able to elaborate on what this means? I'm unsure where these settings are?

**Comment by jcs090218** [comment]
See https://github.com/emacs-openai/codegpt/issues/16.

**Comment by jcs090218** [comment]
Did you figure things out? Let me know if you have other question!

**Comment by joshagudo** [comment]
Sorry @jcs090218 for not replying sooner. 

Yes all sorted, thank you for supplying the linnk.

**Comment by jcs090218** [comment]
No worries! I am happy to help! :D 

Closing this issue now! ;)
